// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxizdnoiyxecbygkqhsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4aXpkbm9peXhlY2J5Z2txaHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIwMjAsImV4cCI6MjA3Mzg2ODAyMH0.aAlo1ukRWBeh2xP4aDAc5iiwd-E_FkPnISYa-yJyvY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});